export enum Currency {

    AFN = "afn", // Afghan Afghani, AFN*
    ALL = "all", // Albanian Lek, ALL
    DZD = "dzd", // Algerian Dinar, DZD
    AOA = "aoa", // Angolan Kwanza, AOA*
    ARS = "ars", // Argentine Peso, ARS*
    AMD = "amd", // Armenian Dram, AMD
    AWG = "awg", // Aruban Florin, AWG
    AUD = "aud", // Australian Dollar, AUD
    AZN = "azn", // Azerbaijani Manat, AZN
    BSD = "bsd", // Bahamian Dollar, BSD
    BDT = "bdt", // Bangladeshi Taka, BDT
    BBD = "bbd", // Barbadian Dollar, BBD
    BZD = "bzd", // Belize Dollar, BZD
    BMD = "bmd", // Bermudian Dollar, BMD
    BOB = "bob", // Bolivian Boliviano, BOB*
    BAM = "bam", // Bosnia & Herzegovina Convertible Mark, BAM
    BWP = "bwp", // Botswana Pula, BWP
    BRL = "brl", // Brazilian Real, BRL*
    GBP = "gbp", // British Pound, GBP
    BND = "bnd", // Brunei Dollar, BND
    BGN = "bgn", // Bulgarian Lev, BGN
    BIF = "bif", // Burundian Franc, BIF
    KHR = "khr", // Cambodian Riel, KHR
    CAD = "cad", // Canadian Dollar, CAD
    CVE = "cve", // Cape Verdean Escudo, CVE*
    KYD = "kyd", // Cayman Islands Dollar, KYD
    XAF = "xaf", // Central African Cfa Franc, XAF
    XPF = "xpf", // Cfp Franc, XPF*
    CLP = "clp", // Chilean Peso, CLP*
    CNY = "cny", // Chinese Renminbi Yuan, CNY
    COP = "cop", // Colombian Peso, COP*
    KMF = "kmf", // Comorian Franc, KMF
    CDF = "cdf", // Congolese Franc, CDF
    CRC = "crc", // Costa Rican Colón, CRC*
    HRK = "hrk", // Croatian Kuna, HRK
    CZK = "czk", // Czech Koruna, CZK*
    DKK = "dkk", // Danish Krone, DKK
    DJF = "djf", // Djiboutian Franc, DJF*
    DOP = "dop", // Dominican Peso, DOP
    XCD = "xcd", // East Caribbean Dollar, XCD
    EGP = "egp", // Egyptian Pound, EGP
    ETB = "etb", // Ethiopian Birr, ETB
    EUR = "eur", // Euro, EUR
    FKP = "fkp", // Falkland Islands Pound, FKP*
    FJD = "fjd", // Fijian Dollar, FJD
    GMD = "gmd", // Gambian Dalasi, GMD
    GEL = "gel", // Georgian Lari, GEL
    GIP = "gip", // Gibraltar Pound, GIP
    GTQ = "gtq", // Guatemalan Quetzal, GTQ*
    GNF = "gnf", // Guinean Franc, GNF*
    GYD = "gyd", // Guyanese Dollar, GYD
    HTG = "htg", // Haitian Gourde, HTG
    HNL = "hnl", // Honduran Lempira, HNL*
    HKD = "hkd", // Hong Kong Dollar, HKD
    HUF = "huf", // Hungarian Forint, HUF*
    ISK = "isk", // Icelandic Króna, ISK
    INR = "inr", // Indian Rupee, INR*
    IDR = "idr", // Indonesian Rupiah, IDR
    ILS = "ils", // Israeli New Sheqel, ILS
    JMD = "jmd", // Jamaican Dollar, JMD
    JPY = "jpy", // Japanese Yen, JPY
    KZT = "kzt", // Kazakhstani Tenge, KZT
    KES = "kes", // Kenyan Shilling, KES
    KGS = "kgs", // Kyrgyzstani Som, KGS
    LAK = "lak", // Lao Kip, LAK*
    LBP = "lbp", // Lebanese Pound, LBP
    LSL = "lsl", // Lesotho Loti, LSL
    LRD = "lrd", // Liberian Dollar, LRD
    MOP = "mop", // Macanese Pataca, MOP
    MKD = "mkd", // Macedonian Denar, MKD
    MGA = "mga", // Malagasy Ariary, MGA
    MWK = "mwk", // Malawian Kwacha, MWK
    MYR = "myr", // Malaysian Ringgit, MYR
    MVR = "mvr", // Maldivian Rufiyaa, MVR
    MRO = "mro", // Mauritanian Ouguiya, MRO
    MUR = "mur", // Mauritian Rupee, MUR*
    MXN = "mxn", // Mexican Peso, MXN*
    MDL = "mdl", // Moldovan Leu, MDL
    MNT = "mnt", // Mongolian Tögrög, MNT
    MAD = "mad", // Moroccan Dirham, MAD
    MZN = "mzn", // Mozambican Metical, MZN
    MMK = "mmk", // Myanmar Kyat, MMK
    NAD = "nad", // Namibian Dollar, NAD
    NPR = "npr", // Nepalese Rupee, NPR
    ANG = "ang", // Netherlands Antillean Gulden, ANG
    TWD = "twd", // New Taiwan Dollar, TWD
    NZD = "nzd", // New Zealand Dollar, NZD
    NIO = "nio", // Nicaraguan Córdoba, NIO*
    NGN = "ngn", // Nigerian Naira, NGN
    NOK = "nok", // Norwegian Krone, NOK
    PKR = "pkr", // Pakistani Rupee, PKR
    PAB = "pab", // Panamanian Balboa, PAB*
    PGK = "pgk", // Papua New Guinean Kina, PGK
    PYG = "pyg", // Paraguayan Guaraní, PYG*
    PEN = "pen", // Peruvian Nuevo Sol, PEN*
    PHP = "php", // Philippine Peso, PHP
    PLN = "pln", // Polish Złoty, PLN
    QAR = "qar", // Qatari Riyal, QAR
    RON = "ron", // Romanian Leu, RON
    RUB = "rub", // Russian Ruble, RUB
    RWF = "rwf", // Rwandan Franc, RWF
    STD = "std", // São Tomé and Príncipe Dobra, STD
    SHP = "shp", // Saint Helenian Pound, SHP*
    SVC = "svc", // Salvadoran Colón, SVC*
    WST = "wst", // Samoan Tala, WST
    SAR = "sar", // Saudi Riyal, SAR
    RSD = "rsd", // Serbian Dinar, RSD
    SCR = "scr", // Seychellois Rupee, SCR
    SLL = "sll", // Sierra Leonean Leone, SLL
    SGD = "sgd", // Singapore Dollar, SGD
    SBD = "sbd", // Solomon Islands Dollar, SBD
    SOS = "sos", // Somali Shilling, SOS
    ZAR = "zar", // South African Rand, ZAR
    KRW = "krw", // South Korean Won, KRW
    LKR = "lkr", // Sri Lankan Rupee, LKR
    SRD = "srd", // Surinamese Dollar, SRD*
    SZL = "szl", // Swazi Lilangeni, SZL
    SEK = "sek", // Swedish Krona, SEK
    CHF = "chf", // Swiss Franc, CHF
    TJS = "tjs", // Tajikistani Somoni, TJS
    TZS = "tzs", // Tanzanian Shilling, TZS
    THB = "thb", // Thai Baht, THB
    TOP = "top", // Tongan Paʻanga, TOP
    TTD = "ttd", // Trinidad and Tobago Dollar, TTD
    TRY = "try", // Turkish Lira, TRY
    UGX = "ugx", // Ugandan Shilling, UGX
    UAH = "uah", // Ukrainian Hryvnia, UAH
    AED = "aed", // United Arab Emirates Dirham, AED
    USD = "usd", // United States Dollar, USD
    UYU = "uyu", // Uruguayan Peso, UYU*
    UZS = "uzs", // Uzbekistani Som, UZS
    VUV = "vuv", // Vanuatu Vatu, VUV
    VND = "vnd", // Vietnamese Đồng, VND
    XOF = "xof", // West African Cfa Franc, XOF*
    YER = "yer", // Yemeni Rial, YER
    ZMW = "zmw"  // Zambian Kwacha, ZMW
}